name: CI

on: [push, pull_request]

jobs:
  test:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, '*']

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm test
      env:
        CI: true

  publish:

    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && ! contains(toJSON(github.event.commits.*.message), '[skip-ci]')

    needs: test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT}}

    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.PAT}}
        git-user-name: github-actions[bot]
        git-user-email: github-actions[bot]@users.noreply.github.com
        git-message: 'bump version and tag for release: {version} [skip-ci]'
        preset: 'angular'
        tag-prefix: ''
        output-file: 'CHANGELOG.md'
    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}